version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
      - sam deploy --template-file packaged.yaml --stack-name ServerlessWebAppStack --capabilities CAPABILITY_IAM
